service: rest-api

provider:
  name: aws
  runtime: nodejs12.x 
  memorySize: 128 
  timeout: 10 
  stage: dev 
  region: us-east-1

functions: 
  createUser:
    handler: handler.createUser # point to exported create function in handler.js
    events:
      - http:
          path: users
          method: post
          cors: true
  createTransaction:
    handler: handler.createTransaction # point to exported create function in handler.js
    events:
      - http:
          path: transactions
          method: post
          cors: true
  getAllTransaction:
    handler: handler.getAllTransaction # point to exported create function in handler.js
    events:
      - http:
          path: transactions
          method: get
          cors: true


plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation
